### ISSUE TITLE
How to Register IPipelineBehavior Validation with MediatR using ErrorOr<TResult> instead TResult

### ISSUE THREAD

**Issue by AleksandarDevic** [amantinband/error-or#10]
Hi, 

I tried to implement MeaditR Commands/Queries Validator with ErrorOr library. Follow your documentation [https://github.com/amantinband/error-or#dropping-the-exceptions-throwing-logic] with some little changes(in bold) ValidationBehavior class is below:

public class ValidationBehavior<TRequest, TResult> : IPipelineBehavior<TRequest, ErrorOr<TResult>>
    where TRequest : IRequest<ErrorOr<TResult>>
{
    private readonly IValidator<TRequest>? _validator;

    public ValidationBehavior(IValidator<TRequest>? validator = null)
    {
        _validator = validator;
    }

    public async Task<ErrorOr<TResult>> Handle(
        TRequest request,
        CancellationToken cancellationToken,
        RequestHandlerDelegate<ErrorOr<TResult>> next)
    {
        if (_validator == null)
        {
            return await next();
        }

        var validationResult = **await** _validator.**ValidateAsync**(request);

        if (validationResult.**IsValid**)
        {
            return validationResult.Errors
               .ConvertAll(validationFailure => Error.Validation(
                   code: validationFailure.PropertyName,
                   description: validationFailure.ErrorMessage));
        }

        return await next();
    }
}

But above mentioned class never triggered.

Static class ConfigureServices.cs where is services registered is below: 

using System.Reflection;
using FluentValidation;
using MediatR;

namespace Microsoft.Extensions.DependencyInjection;
public static class ConfigureServices
{
    public static IServiceCollection AddApplicationServices(this IServiceCollection services)
    {
        services.AddHttpContextAccessor();

        services.AddValidatorsFromAssembly(Assembly.GetExecutingAssembly());
        services.AddMediatR(Assembly.GetExecutingAssembly());

        services.AddTransient(typeof(IPipelineBehavior<,>), typeof(ValidationBehavior<,>));

        return services;
    }
}

Please can you give me advice how to properly register ValidationBehavior class ?

Thanks in advance. :-)

**Comment by grufffta** [comment]
shouldn't it be 
```csharp
public class ValidationBehavior<TRequest, TResult> : IPipelineBehavior<TRequest, ErrorOr<TResutl>>
```

**Comment by amantinband** [comment]
Thanks, @AleksandarDevic for opening this issue. You are right, the previously documented implementation wasn't invoked.
Unfortunately, same as others facing similar issues (https://github.com/jbogard/MediatR/issues/626, https://github.com/jbogard/MediatR/issues/562, https://github.com/jbogard/MediatR/issues/182, https://github.com/jbogard/MediatR/issues/701, ..), I wasn't able to find a way around this that didn't use reflection. I've updated the documentation with the cleanest solution I was able to create. Let me know if you have a better idea or run into any issues 🤙

**Comment by grufffta** [comment]
I found one way around using a `dynamic` type.
```csharp
public class ErrorOrPipelineBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
    where TRequest : IRequest<TResponse>
{
    public async Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
    {
        (dynamic result, var isError) = Validate(request);
        
         if (isError)
         {
             return result;
         }
        return await next();
    }

    private (List<Error> errors, bool isError) Validate(TRequest request)
    {
        var errors = new List<Error> { Error.Conflict() };
        return (errors, errors.Any());
    }
}
```

**Comment by AleksandarDevic** [comment]
Hi, @amantinband, with your new version of this package and using reflection, problem is resolved. 👍 Thanks you. :-)

**Comment by amantinband** [comment]
> I found one way around using a `dynamic` type.
> 
> ```cs
> public class ErrorOrPipelineBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
>     where TRequest : IRequest<TResponse>
> {
>     public async Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
>     {
>         (dynamic result, var isError) = Validate(request);
>         return isError ? (TResponse)result : await next();
>     }
> 
>     private (List<Error> errors, bool isError) Validate(TRequest request)
>     {
>         var errors = new List<Error> { Error.Conflict() };
>         return (errors, errors.Any());
>     }
> }
> ```

@grufffta, Ooh that's cool. Didn't know that would work!

I'm not sure if something like this is a cleaner though:

```csharp
public class ValidationBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
    where TRequest : IRequest<TResponse>
    where TResponse : IErrorOr
{
    private readonly IValidator<TRequest>? _validator;

    public ValidationBehavior(IValidator<TRequest>? validator = null)
    {
        _validator = validator;
    }

    public async Task<TResponse> Handle(
        TRequest request,
        CancellationToken cancellationToken,
        RequestHandlerDelegate<TResponse> next)
    {
        if (_validator == null)
        {
            return await next();
        }

        var validationResult = await _validator.ValidateAsync(request, cancellationToken);

        if (validationResult.IsValid)
        {
            return await next();
        }

        return TryCreateErrorResponseFromErrors(validationResult.Errors, out var errorResponse)
            ? errorResponse
            : throw new ValidationException(validationResult.Errors);
    }

    private static bool TryCreateErrorResponseFromErrors(List<ValidationFailure> validationFailures, out TResponse errorResponse)
    {
        List<Error> errors = validationFailures
            .ConvertAll(x => Error.Validation(code: x.PropertyName, description: x.ErrorMessage));

        try
        {
            errorResponse = (TResponse)(dynamic)errors;
            return true;
        }
        catch
        {
            errorResponse = default!;
            return false;
        }
    }
}
```
WDYT?

**Comment by grufffta** [comment]
I think that looks nice and clean compared to having the reflection calls. I believe dynamic is using reflection under the covers but the CLR will cache the calls automatically for performance. 

Thanks for your work on this library and the YT series too :)

Gareth

**Comment by Germandf** [comment]
I ended up doing something inspired by Amichai's snippet and this [article](https://medium.com/@mxcmxc/unit-of-work-with-the-repository-pattern-boilerplate-part-2-b7ae88ec071c). In case someone finds it useful, i'll leave it here:

### ExceptionBehavior.cs

``` csharp
public class ExceptionBehavior<TRequest, TResponse> :
    IPipelineBehavior<TRequest, TResponse>
       where TRequest : IRequest<TResponse>
       where TResponse : IErrorOr
{
    private readonly ILogger<ExceptionBehavior<TRequest, TResponse>> _logger;

    public ExceptionBehavior(ILogger<ExceptionBehavior<TRequest, TResponse>> logger)
    {
        _logger = logger;
    }

    public async Task<TResponse> Handle(
        TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
    {
        try
        {
            return await next(request, cancellationToken);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Exception catched in ExceptionBehavior");

            return Error.Unexpected(description: ex.Message).ToTResponse<TResponse>();
        }
    }
}
```

### ValidationBehavior.cs

``` csharp
public class ValidationBehavior<TRequest, TResponse> : 
    IPipelineBehavior<TRequest, TResponse>
       where TRequest : IRequest<TResponse>
       where TResponse : IErrorOr
{
    private readonly IEnumerable<IValidator<TRequest>> _validators;

    public ValidationBehavior(IEnumerable<IValidator<TRequest>> validators)
    {
        _validators = validators;
    }

    public async Task<TResponse> Handle(
        TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
    {
        var context = new ValidationContext<TRequest>(request);

        var validationFailures = _validators
            .Select(v => v.Validate(context))
            .SelectMany(result => result.Errors)
            .Where(f => f != null)
            .ToList();

        if (validationFailures.Any())
        {
            var errors = validationFailures.Select(x => Error.Conflict(x.ErrorCode, x.ErrorMessage)).ToList();

            return errors.ToTResponse<TResponse>();
        }

        return await next(request, cancellationToken);
    }
}
```

### ErrorOrExtensions.cs

``` csharp
public static class ErrorOrExtensions
{
    public static TResponse ToTResponse<TResponse>(this Error error)
    {
        var errors = new List<Error> { error };

        return errors.ToTResponse<TResponse>();
    }

    public static TResponse ToTResponse<TResponse>(this List<Error> errors)
    {
        var response = (TResponse?)typeof(TResponse)
            .GetMethod(
                name: nameof(ErrorOr<object>.From),
                bindingAttr: BindingFlags.Static | BindingFlags.Public,
                types: new[] { typeof(List<Error>) })?
            .Invoke(null, new[] { errors })!;

        return response;
    }
}
```

### Program.cs

```csharp
builder.Services.AddMediatR(typeof(Program))
    .AddScoped(typeof(IPipelineBehavior<,>), typeof(ExceptionBehaviour<,>))
    .AddScoped(typeof(IPipelineBehavior<,>), typeof(ValidationBehaviour<,>));
```
