### ISSUE TITLE
[Question]: Should it be possible to instantiate ErrorOr<TValue> with an empty error list?

### ISSUE THREAD

**Issue by feO2x** [amantinband/error-or#100]
First of all, thanks for all your efforts that you put into this library!

I have the following question: in version 2.0.1 of ErrorOr, the following test succeeds:

```csharp
[Fact]
public void CreateWithErrors_WhenErrorsListIsEmpty_ShouldRaiseAnError()
{
    ErrorOr<Person> errorOrPerson = new List<Error>();

    errorOrPerson.IsError.Should().BeTrue();
    errorOrPerson.Match(
        validValue => throw new Exception("We should not reach this line of code"),
        errors => { /* errors is an empty list here */ });
}
```

In it, I instantiate an empty error list and implicitly convert it to an `ErrorOr<Person>` instance. I think this is invalid behavior: my expectation would be to have at least one item in the errors collection when `IsError` returns true. In fact, to make the above a proper test, I would actually use `errors => errors.Should().NotBeEmpty();`.

However, which error do we insert into the errors collection of the `ErrorOr<TValue>` instance when an empty collection is passed? Personally, I'd argue that we should throw an exception when invalid values are passed to an `ErrorOr<TValue>` instance but I guess you don't want to do that because the whole idiom of this library is not using exceptions. Still, I'd say that passing an empty collection is an error in how the calling dev uses the library and should be distinguished from actual domain-specific errors.

I'm interested in your opinion on this.

**Comment by amantinband** [comment]
Wow that's a good catch and a good question.

I agree that the current behavior is weird. Especially since we are saying `IsError` is `true`, and yet the errors list is empty.

Basically the options are:
1. Throw an exception in implicit converter
2. Mark IsError as false if the list is empty (which means validValue will be default)
3. Mark IsError as false if the list is empty, and insert a default error indicating this happened
4. Leave as is

I don't have a strong opinion either way since I don't like any of the options tbh

**Comment by feO2x** [comment]
I would throw an exception in the implicit converters. This is not a domain-specific error, but the library being called/used in a wrong way. If you don't mind, I would prepare a PR for you this evening?

**Comment by amantinband** [comment]
Right, but the same can be argued for throwing an exception when accessing the `Value` when `IsError` is true
<img width="260" alt="image" src="https://github.com/amantinband/error-or/assets/39407673/45f73afd-2058-440f-bdfc-c0c5e88848b9">

If we go with this, I would also align the other places as well.

I don't have a strong opinion either way, but I think the behavior should be consistent, wdyt?

**Comment by amantinband** [comment]
This also has to do with #102. If we go with exceptions, default ctor should throw an exception as well

**Comment by amantinband** [comment]
> I would throw an exception in the implicit converters. This is not a domain-specific error, but the library being called/used in a wrong way. If you don't mind, I would prepare a PR for you this evening?

I started playing with this to get the feel #105

**Comment by feO2x** [comment]
Sorry for the delay, I'm currently on a hike. I would throw exceptions in all cases you mentioned. The reasoning behind this is simply Bertrand Mayers Design by Contract: certain invariants are in effect after an `ErrorOr<T>` instance is created and callers need to use the correct APIs for accessing the value or the errors depending on the invariants.

**Comment by amantinband** [comment]
Cool, enjoy! Yeah I tend to agree, and this is the design I originally went with

**Comment by amantinband** [comment]
List cannot be empty enforcement added as part of #105. Will be available as part of ErrorOr 3.x
