### ISSUE TITLE
Breaking Change in v2.1 / Serializing to json

### ISSUE THREAD

**Issue by swolf91** [amantinband/error-or#115]
In the newest version 2.1 is a breaking change that is not listed in the changelog.

Before - with version 2.0.1 - the ErrorOr<> Properties `Value` and `Errors` could be returned always.
For the Errors an error was returned with the description: "Error list cannot be retrieved from a successful ErrorOr".

Now the call to `Errors` when `IsError` is `false` throws an exception. The same goes for the call to `Value` when `IsError` is `true`

This results now in an exception when serializing an ErrorOr value to a json string.
Is this something that you want to fix in the library and just did not notice yet or do I have to care for it in my own code? I would prefer to have a fix here. 

# Reproduce

call the following code with ErrorOr version 2.1.0: 

```cs
ErrorOr<int> value = 42;
Console.WriteLine(JsonSerializer.Serialize(value));
```

to get the exception:

```
Unhandled exception. System.InvalidOperationException: The Errors property cannot be accessed when no errors have been recorded. Check IsError before accessing Errors.
   at ErrorsGetter(Object)
```

# Before

With version 2.0.1 this resulted in the string:

```cs 
{"IsError":false,"Errors":[{"Code":"ErrorOr.NoErrors","Description":"Error list cannot be retrieved from a successful ErrorOr.","Type":1,"NumericType":1,"Metadata":null}],"ErrorsOrEmptyList":[],"Value":42,"FirstError":{"Code":"ErrorOr.NoFirstError","Description":"First error cannot be retrieved from a successful ErrorOr.","Type":1,"NumericType":1,"Metadata":null}}
```

**Comment by amantinband** [comment]
Wow.. my bad. Completely forgot about all the breaking changes we've made a few months ago. These should all be under ErrorOr 3.x. I've unlisted the package on NuGet and will revert the release here on GitHub as well. Thanks for taking the time and opening this issue.

I'm on vacation, so will release 3.x properly later on.

**Comment by swolf91** [comment]
thank you. I think that means that we have to care for serialization on our own and create an own converter with ErrorOr 3.x.

Well but @amantinband one "important" thing. I think that you removed the wrong release on GitHub. You removed the release for 2.0.1. For 2.1.0 there was no release on GitHub yet, I guess. There were only the release commits (version and changelog).

Have a nice vacation
