### ISSUE TITLE
Cannot implicitly convert type with IEnumerable

### ISSUE THREAD

**Issue by Rasphino** [amantinband/error-or#13]
Hi Amichai, I have a problem when trying to wrap an `IEnumerable` to an `ErrorOr<IEnumerable>`: 

```C#
using ErrorOr;

class Foo {
    public ErrorOr<IEnumerable<int>> wrap() {
        IEnumerable<int> nums = new List<int>(){ 1, 2 };
        return nums;   
    }
}
```

VSCode gives me an error:
```
Cannot implicitly convert type 'System.Collections.Generic.IEnumerable<int>' to 'ErrorOr.ErrorOr<System.Collections.Generic.IEnumerable<int>>' [BuberDinner.Api]csharp(CS0029)
No quick fixes available
```

-----

I find a workaround: changes `IEnumerable<int> tools` to `List<int> tools`:
```C#
using ErrorOr;

class Foo {
    public ErrorOr<IEnumerable<int>> wrap() {
        List<int> nums = new List<int>(){ 1, 2 };
        return nums;   
    }
}
```

**Comment by jorik** [comment]
I'm getting the same error:

```csharp
public async Task<ErrorOr<IReadOnlyList<Dto>>> DoSomething(...) 
{
    var list = await _repository.Get();
    return list.AsDto();
}


 internal static IReadOnlyList<Dto> AsDto(this IEnumerable<DbObject> dbObjects) {
     return dbObjects.Select(AsDto).ToList();
 }
```

Getting this error:
`cannot convert expression type 'System.Collections.Generic.IReadOnlyList<Dto>' to return type 'ErrorOr.ErrorOr<System.Collections.Generic.IReadOnlyList<Dto>>'`

**Comment by amantinband** [comment]
Thanks, @Rasphino, for opening this issue. You are right, implicit conversion won't work with interfaces. I've added an `ErrorOr.From` method. I'll publish a new version and update the documentation 🙂

**Comment by amantinband** [comment]
Done: https://github.com/amantinband/error-or#from-value-using-from

Let me know if you still face any issues.

**Comment by dozed** [comment]
It seems the `From` method currently only supports the creation from a list of errors, the construction with values doesn't seem to be implemented.

https://github.com/amantinband/error-or/blob/main/src/ErrorOr.cs#L29-L35

**Comment by amantinband** [comment]
@dozed, have you tried `ErrorOr.From(value)` ([docs](https://github.com/amantinband/error-or#from-value-using-from), [source code](https://github.com/amantinband/error-or/blob/f74b7af561381c0934efde15f90117ad359d8c0b/src/ErrorOr.cs#L153))?
It's implemented this way, so you don't need to write `ErroOr<ValueType>.From(value)`

**Comment by dozed** [comment]
For some reason this does not compile:

![image](https://user-images.githubusercontent.com/239058/185560269-62ccd922-e181-4601-ac6b-80003929aa33.png)

Whereas this does:

![image](https://user-images.githubusercontent.com/239058/185560330-f7c75db1-edaf-475f-85ae-92376ec997b6.png)

Am I doing something wrong here?

**Comment by bwong365** [comment]
Same here: `ErrorOr.From(data)` fails to compile while `ErrorOr.ErrorOr.From(data)` works. It's not the worst; but it does look pretty awkward.

**Comment by chrisgilliam72** [comment]
try ErrorOrFactory.From(data)
