### ISSUE TITLE
Extend ErrorType enum

### ISSUE THREAD

**Issue by DimetilTriptAmin** [amantinband/error-or#14]
It would be great to have all the type of errors that could be mapped to 4xx status code series

**Comment by amantinband** [comment]
Hi @DimetilTriptAmin, you can already achieve this by using the `Error.Custom` static factory method and accessing the `ErrorOr.NumericType`

![image](https://user-images.githubusercontent.com/39407673/184547886-43a2f6a8-43cd-4698-98d0-a72cd5a4706b.png)

**Comment by amantinband** [comment]
Let me know if this solves your needs :)

**Comment by DimetilTriptAmin** [comment]
Works for me, thanks
