### ISSUE TITLE
ErrorType of Cancelled

### ISSUE THREAD

**Issue by gslam2k** [amantinband/error-or#19]
Awesome videos and NuGet package.
It would be nice to have a cancelled error type to handle the user cancelled scenarios for APIs etc

**Comment by vpekarek** [comment]
Hi, you can use the `NumericType ` property on `Error` with `ErrorType.Custom`. Then you can have your enum with other types of errors, like `Cancelled`, etc.
Then you can check the error `NumericType` against this enum.

**Comment by FAdrianJ** [comment]
I am doing this currently, but switching is a bit convoluted.

**Comment by amantinband** [comment]
@FAdrianJ, do you use the enum and your custom types together? Or do you use only your custom types and you find working with the `NumbericType` is convoluted?

**Comment by amantinband** [comment]
Closing as not planned
