### ISSUE TITLE
Error Type Of Void

### ISSUE THREAD

**Issue by imranshabbir** [amantinband/error-or#21]
Thanks for your nice videos.
How i can use this if i dont have to return anything except errors?

**Comment by sean-vogel** [comment]
I believe you use ErrorOr<Success> as the return type.

**Comment by amantinband** [comment]
Hi @imranshabbir, as @sean-vogel suggested, you can use the `Success`/`Deleted`/.. types that you have out of the box, or create something similar that answers your needs
