### ISSUE TITLE
`ErrorOr.From(data)` does not compile

### ISSUE THREAD

**Issue by bwong365** [amantinband/error-or#33]
The example shown in the docs (https://github.com/amantinband/error-or#from-value-using-from) does not actually compile, and results in `The type or namespace name 'From' does not exist in the namespace 'ErrorOr' (are you missing an assembly reference?)`. Currently we have to use `ErrorOr.ErrorOr.From(data)` instead.

![image](https://user-images.githubusercontent.com/42486090/195782093-50eac196-0a87-4be8-9add-52c1c423c65b.png)

**Comment by florentmx** [comment]
Add `using ErrorOr;` and the first one will compile, or you can simply `return 5;` which will be converted to `ErrorOr<int>`

**Comment by bwong365** [comment]
The example does include the using statement
![image](https://user-images.githubusercontent.com/42486090/200131289-3e519848-7f5c-4f70-85f5-37bcd0e65270.png)

You can indeed simply return 5, but this issue is that the docs contain an example that doesn't compile.

**Comment by florentmx** [comment]
Oh, I think you are right in that case. You could submit a PR which fixes the docsOn 5. Nov 2022, at 17:43, Ben Wong ***@***.***> wrote:﻿
The example does include the using statement

You can indeed simply return 5, but this issue is that the docs contain an example that doesn't compile.

**Comment by amantinband** [comment]
Yeah, sorry about that, I noticed this a while back and didn't get to it yet. The namespace and the static class name being the same requires disambiguation (this has also been discussed here: #13)

I haven't decided yet how to go about this. Feel free to suggest any alternative you wish :)

**Comment by amantinband** [comment]
I decided to go with `ErrorOrFactory.From`.
To avoid breaking changes, this lives alongside the `ErrorOr.ErrorOr.Value` solution, but the documentation was updated to describe only the factory solution.
