### ISSUE TITLE
Usage of Library to Replace null return type

### ISSUE THREAD

**Issue by squadwuschel** [amantinband/error-or#48]
Hi,

I think it's more an overall question/suggestion :-). 
Was this library also created to replace null return types in my application or just to prevent to throw exceptions and get better Error Results?
Because if I would use this to prevent null return types I think the basic naming "ErrorOr" is not the best, when you read "everywhere" in your ValueObjects oder DomainLogic "ErrorOr<>" return type looks strange.

**Comment by amantinband** [comment]
Hey @squadwuschel!

Yep, this library was intended to replace throwing exceptions, not "not returning null" cases.
