### ISSUE TITLE
Add the Property IsSuccess like IsError

### ISSUE THREAD

**Issue by squadwuschel** [amantinband/error-or#49]
Would be nice if there could be a IsSuccess Property like the IsError Property.

**Comment by asevos** [comment]
Maybe implementing a simple extension would help with this: 

```csharp
public static class ErrorOrExtensions
{
	public static bool IsSuccess<T>(this ErrorOr<T> error) => !error.IsError;
}
```

**Comment by dragoaus** [comment]
Can I pick this issue?

**Comment by amantinband** [comment]
Hey guys. I prefer having only the `IsError` property.

My motivation is pushing people to write code like this:

```csharp
if (result.IsError)
{
    return result.Errors;
}

// is success logic - often multiple LOC
```

Instead of this:

```csharp
if (result.IsSuccess)
{
    // is success logic - often multiple LOC
}

return result.Errors;
```

Let me know what you think

**Comment by dragoaus** [comment]
When you put it like that I agree, having IsSucess is redundant.
