### ISSUE TITLE
Question: `ErrorOr<>.Errors` as readonly collection

### ISSUE THREAD

**Issue by wdolek** [amantinband/error-or#50]
Is `ErrorOr` designed so that you can mutate its state (`List<Error> Errors`), or is there any other reason for this design choice?

Using `IReadOnlyList<>` (or even `IReadOnlyCollection<>` if accessing very first error is not needed) would improve (imo):

1. Signature - giving hint that this is immutable data structure
2. No need for allocating new `List<Error>` when accessing errors (though this should be relatively [cheap](https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/List.cs,30), but still additional allocation)
   - both caching no errors list and empty one
3. Only drawback I can see is that to ensure no one tempers with input, copy of input list is needed (in ctor `ErrorOr(List<Error> errors)`)

I'm really interested knowing specific reason (of course changing it to `IReadOnly*` is breaking, obviously)

**Comment by amantinband** [comment]
Hey @wdolek! We've discussed this topic here: #26
