### ISSUE TITLE
Cannot implicitly convert type IQueryable<T> to ErrorOr.ErrorOr<IQueryable<T>>

### ISSUE THREAD

**Issue by fernandobracaroto** [amantinband/error-or#56]
Hi, thank You for this awesome library.
I'm having trouble implementing a get request handler, the code as follow: 

```
public class GetQueryHandler :
    IRequestHandler<GetQuery, ErrorOr<IQueryable<User>>>
{
    private readonly IApplicationDbContext _context;

    public GetQueryHandler(IApplicationDbContext context)
    {
        _context = context;
    }

    public async Task<ErrorOr<IQueryable<User>>> Handle(
        GetQuery request,
        CancellationToken cancellationToken)
    {
        await Task.CompletedTask;
        return _context.Users.AsQueryable();
    }
}

```

Throws the error cannot implicitly convert type IQueryable<T> to ErrorOr.ErrorOr<IQueryable<T>>.
If I change the IQueryable to IList and change the return to _context.Users.ToList() it works.

**Comment by Tusankata** [comment]
Can confirm I am having the exact same issue, 1:1.
Can also confirm that changing to IList works.

**Comment by sgwong** [comment]
I am having similar issue, it also cannot implicit convert type `IEnumerable<T>`

**Comment by thinker227** [comment]
Implicit conversion operators cannot be to or from interface types. From the [10.5 of the C# spec](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/conversions#105-user-defined-conversions):

> A class or struct is permitted to declare a conversion from a source type S to a target type T only if all of the following are true:
> [...]
> - Neither S₀ nor T₀ is an interface_type.

**Comment by amantinband** [comment]
Closing this issue. Feel free to reopen or comment if you still have any questions 🙂
