### ISSUE TITLE
Add ability to show result and errors

### ISSUE THREAD

**Issue by kh-csyms** [amantinband/error-or#58]
Unless I'm missing something, it would be nice to be able to use both value and errors. In the specific scenario I'm imagining, one would try to "BatchUpdate" via the API:

The command handler runs through and verifies that each object exists in the database exists (or not). For each item that doesn't exist in the database, generate an error, and for each item that does exist, go ahead and update. The handler then returns both the successes and failures (errors), that can be mapped to a response. 

Similar to another issue, this would allow us to use IsError to set the Success to false on the response, but show errors and success values.

**Comment by r14958** [comment]
ErrorOr is simulating a "discriminated union" in C#, in which the returned object can either be one type (in this case, an Error) "or" another type (thus the name).  The whole point of ErrorOr is to never allow the creation of an invalid type.  It sounds like you are trying track a collection of types, so perhaps you want to return a collection of ErrorOr<type>?

**Comment by amantinband** [comment]
As @r14958 responded, I would suggest returning a collection of ErrorOr objects for this scenario.

Each `ErrorOr` object can be in one of two states, and doesn't support storing both errors and results.
