### ISSUE TITLE
How can I create an Error type that has exception data?

### ISSUE THREAD

**Issue by stannynuytkens** [amantinband/error-or#62]
What I want to achieve is something similar as:

![problemdetails-json-exception-dev-3](https://github.com/amantinband/error-or/assets/85672679/3962d385-8280-4af9-aca5-5bbbae21c63d)

_from [Hellang.Middleware.ProblemDetails](https://www.nuget.org/packages/Hellang.Middleware.ProblemDetails)_

Now, the problem is I should only expose the exception data with certain environments so set the exception on an Error type in the repository and choose to show it in ... the ApiProblemDetailsFactory?

```try
        {
            var response = await _orderClient.SummaryAsync(orderNumber);
            
            if(_logger.IsEnabled(LogLevel.Debug))
                _logger.LogDebug("Retrieved shipping information for order {orderNumber}", orderNumber);
            
            return _mapper.Map<Domain.Shipping.ShippingInformation.ShippingInformation>(response);
        }
        catch (ApiClientCallException apiClientCallException) when (apiClientCallException.StatusCode == 404)
        {
            if(_logger.IsEnabled(LogLevel.Information))
                _logger.LogInformation("Order {orderNumber} not found", orderNumber);
            
            return Errors.Shipping.OrderNotFound;
        }
        catch (Exception e)
        {
            if(_logger.IsEnabled(LogLevel.Error))
                _logger.LogError(e, "Failed to get shipping information for order {orderNumber}", orderNumber);
            
            return Error.Unexpected(); // Add exception here!
        }

**Comment by amantinband** [comment]
Hi @stannynuytkens, version `1.4.0` added the `Metadata` property to the `Error` object, which can be used to store extra details alongside the error #25
