### ISSUE TITLE
Please add a strong name for the assembly

### ISSUE THREAD

**Issue by JZO001** [amantinband/error-or#63]
Hi,
Please add strong name for the assembly. Without it, in 4.x .NET projects without strong name it is not possible to use this library, getting exception:

Could not load file or assembly 'ErrorOr, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
System.IO.FileLoadException: Could not load file or assembly 'ErrorOr, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

**Comment by amantinband** [comment]
Hey @JZO001, I'm not planning on adding support for projects < .NET 6 ATM to keep things simple. Closing as out of scope
