### ISSUE TITLE
Non generic ErrorOr possible?

### ISSUE THREAD

**Issue by DaveArkley-Codiance** [amantinband/error-or#65]
Scattered throughout our code base I see return types of ErrorOr<bool>. I think this comes from legacy code (pre the use of ErrorOr) where the bool indicated success or failure. It strikes me that the presence/absence of errors indicates the same. Is it possible  to return ErrorOr (none-generic)  so I can just test the IsError status to indicate success or failure? I guess it may be an issue with how to return the discriminated union for success because it then becomes ErrorOr<nothing>!

**Comment by martinobordin** [comment]
You could define a class `Success` and, in the various methods, return ErrorOr<Success>. It will also sound better 😊
What's your thought?

**Comment by DylanSnel** [comment]
You can return IErrorOr it contains IsError and the List of errors

**Comment by amantinband** [comment]
Yep, as @DylanSnel suggested, you can return `IErrorOr`
