### ISSUE TITLE
Consider 'Forbidden' as built-in error type

### ISSUE THREAD

**Issue by chrisketelaar** [amantinband/error-or#71]
First of all, thank you very much for creating and maintaining this repository.

I would like to suggest adding an additional built-in error type, namely 'Forbidden,' because I believe that in some situations, it provides a better description than the existing 'Unauthorized.'

I understand that error types don't necessarily have to directly align with HTTP standards, but in this case, it might make more sense. This is what the specifications state:

Unauthorized

> The 401 (Unauthorized) status code indicates that the request has not
  been applied because it lacks valid authentication credentials for
  the target resource.  The server generating a 401 response MUST send
  a WWW-Authenticate header field (Section 4.1) containing at least one
  challenge applicable to the target resource.
  
> If the request included authentication credentials, then the 401
  response indicates that authorization has been refused for those
  credentials.  The user agent MAY repeat the request with a new or
  replaced Authorization header field (Section 4.2).  If the 401
  response contains the same challenge as the prior response, and the
  user agent has already attempted authentication at least once, then
  the user agent SHOULD present the enclosed representation to the
  user, since it usually contains relevant diagnostic information.

Forbidden:

>  The 403 (Forbidden) status code indicates that the server understood
   the request but refuses to authorize it.  A server that wishes to
   make public why the request has been forbidden can describe that
   reason in the response payload (if any).

> If authentication credentials were provided in the request, the
   server considers them insufficient to grant access.  The client
   SHOULD NOT automatically repeat the request with the same
   credentials.  The client MAY repeat the request with new or different
   credentials.  However, a request might be forbidden for reasons
   unrelated to the credentials.

If you agree with my reasoning, I could open a PR to add Forbidden as a built-in type.

I look forward to hearing from you.

edit: 
I know I can potentially add a custom error type myself, but it seemed to me like a valuable addition as a built-in

**Comment by amantinband** [comment]
Hey guys. I intended the "Unauthorized" to mean the user failed some authorization step (not authentication).

I understand why this is confusing given 401 is "Unauthorized" and not "Unauthenticated".

Perhaps "Forbidden" would have been a better name choice. I can rename "Unauthorized" to "Forbidden" if you think it is worth the change, but please note this would be a breaking change.

Let me know would you think.

**Comment by chrisketelaar** [comment]
For me it would make sense to change "Unauthorized" to "Forbidden" because .net is handling authentication for me and authorization is done in layers where I use ErrorOr, but I can't say if that is the case for alle developer which use ErrorOr. 

I think Unauthorized could still be useful for developers which roll there own authentication so maybe Forbidden could be added instead of replacing Unauthorized. Adding will also maintain backwards-compatibility.

**Comment by amantinband** [comment]
added #86
