### ISSUE TITLE
IsError = true; Errors.Length = 0;

### ISSUE THREAD

**Issue by AJax2012** [amantinband/error-or#72]
For some reason, when I return an empty list of Errors, I get IsError = true.

Maybe there's a better way to design this on my end, but I'd like to use ErrorOr<T> methods to also check for null values and return null or at least IsError = false and Value = null when working with domain methods that do things like TryCreate.

Code Snippet:

```csharp
/// <summary>
/// Ensures Positive Integer.
/// </summary>
public class PositiveInt : ValueObject
{
	public int Value { get; }

	public PositiveInt(int value, string propertyName)
	{
		value.Throw(paramName: propertyName).IfNegativeOrZero();
		Value = value;
	}

	/// <summary>
	/// Trys to create <see cref="PositiveInt"/>. Returns Error if it fails.
	/// <remarks>When value is null, will return IsError = true with empty list of errors.</remarks>
	/// </summary>
	/// <param name="value">Value of <see cref="PositiveInt"/>.</param>
	/// <param name="propertyName">Property <see cref="PositiveInt"/> is being assigned to.</param>
	/// <returns><see cref="PositiveInt"/> or Validation Error.</returns>
	public static ErrorOr<PositiveInt> TryCreate(int? value, string propertyName)
	{
		if (!value.HasValue)
		{
			return new List<Error>();
		}

		if (!int.IsPositive(value.Value))
		{
			return Error.Validation("PositiveInt.Invalid", $"{propertyName} must be larger than 0.");
		}

		return new PositiveInt(value.Value, propertyName);
	}

	/// <inheritdoc />
	protected override IEnumerable<object> GetEqualityComponents()
	{
		yield return Value;
	}
}
```

When I create a test where the value property of TryCreate is null, I get `IsError = true` and `actual.ErrorsOrEmptyList.Should().BeEmpty() = true`.

What I'd ideally like to do is just return null, but then I'd have to make the return value for the method `ErrorOr<PositiveInt>?`, which results in a lot of hassle. However, I also feel like I should be able to return an empty list of Error and `IsError` should still be false?

I'm somewhat new to this library, so maybe there's a better way to do what I'm trying to accomplish. I'm open to suggestions.

Thanks!

**Comment by itsC-Ramesh** [comment]
I can understand your point of view, but the fundamental concept behind returning an error is to signal that something isn't right. If you believe that a null value is not an error, you can:

1. Explicitly handle null values and return a result that doesn't indicate an error.
2. Adapt the ErrorOr structure to better match your specific requirements.

In the end, it all comes down to the specific requirements and design of your application along with need for clear error handling. It's essential to use error handling to indicate unexpected or problematic situations while still providing flexibility to handle valid conditions as needed.

**Comment by r14958** [comment]
@AJax2012: The way PositiveInt is defined in you example, its integer value is not nullable, so how can setting its value to null NOT be an error?  If you would would likePositiveInt to accept null without an error, you could rewrite the class like:
```csharp
using CSharpFunctionalExtensions;
using ErrorOr;
using Throw;

namespace TestErrorWithNullValues.ConsoleUI;

/// <summary>
/// Ensures Positive Integer.
/// </summary>
public class PositiveInt : ValueObject
{
    public int? Value { get; }

    public PositiveInt(int? value, string propertyName)
    {
        Value = value is null
            ? value
            : value.Value.Throw(paramName: propertyName).IfNegativeOrZero();
    }

    /// <summary>
    /// Tries to create <see cref="PositiveInt"/>. Returns Error if it fails.
    /// <remarks>When value is null, will return IsError = true with empty list of errors.</remarks>
    /// </summary>
    /// <param name="value">Value of <see cref="PositiveInt"/>.</param>
    /// <param name="propertyName">Property <see cref="PositiveInt"/> is being assigned to.</param>
    /// <returns><see cref="PositiveInt"/> or Validation Error.</returns>
    public static ErrorOr<PositiveInt> TryCreate(int? value, string propertyName)
    {
        if (!value.HasValue)
        {
            return new PositiveInt(value, propertyName);
        }

        if (!int.IsPositive(value.Value))
        {
            return Error.Validation("PositiveInt.Invalid", $"{propertyName} must be larger than 0.");
        }

        return new PositiveInt(value.Value, propertyName);
    }

    protected override IEnumerable<IComparable?> GetEqualityComponents()
    {
        yield return Value;
    }
}
```

Testing this with:

```csharp
using TestErrorWithNullValues.ConsoleUI;

var test = PositiveInt.TryCreate(null, "test");

Console.WriteLine($"{nameof(test)} has an error is: {test.IsError} with value: '{(test.Value.Value is null ? "null" : test.Value.Value)}'.");

//Output: test has an error is: False with value: 'null'.
```

**Comment by AJax2012** [comment]
That wasn't really the point of my post. It also doesn't really accomplish the goal of my code, but the actual problem is, if the list of errors is empty, why is `TryCreate.IsError = true`? If there aren't errors, IsError should be false, no?

Also, dealing with the Value property being nullable would be a pain in my code base, which is why it's not nullable in my code example. This is the domain layer of my code, which means the object (ValueObject in this case) should always be valid. If the Value is nullable, the Value might not always be a PositiveInt, ergo, invalid. Entities using this ValueObjects could be nullalbe, but not the ValueObject itself.

**Comment by r14958** [comment]
For ErrorOr to return IsError = false with a null value  for PositiveInt  you can simply set ErrorOr<PositiveInt> test  = default;

**Comment by r14958** [comment]
Sorry did not use code snippet:
````csharp
ErrorOr<PositiveInt> test2 = default;
````

**Comment by r14958** [comment]
If you don't provide ErrorOr with a value, it will always return IsError = true.

**Comment by AJax2012** [comment]
I'll give default a try; I don't have my computer with me. I still don't know why IsError should be true if there aren't any Errors, but default at least makes sense.

**Comment by r14958** [comment]
Actually, I think you found a minor bug in ErrorOr.  If you set `ErrorOr<T> test = new List<Error>()` and call for `test.FirstError`, ErrorOr will throw a **System.ArgumentOutOfRangeException**, since FirstError looks for index [0] in the list.  It does not check the length of the list first.

Regarding the logic behind the library, ErrorOr is simulating a discriminated union in C#, which is from functional programming.  It must either be an instance of a type Or an Error (or multiple errors) -- just like the name says.  If you give it neither, it should throw an argument exception, although in the case you described its not guarding against an empty list and throwing the wrong exception at the wrong time.

**Comment by AJax2012** [comment]
Looks like default works! I forgot how much this class changed since October, but this was the result:

```csharp
/// <summary>
/// Ensures Positive Integer.
/// </summary>
public class PositiveInt : ValueObject
{
	/// <summary>
	/// Initializes a new instance of the <see cref="PositiveInt"/> class.
	/// </summary>
	/// <param name="value"><see cref="int"/>.</param>
	public PositiveInt(int value)
	{
		value.Throw(paramName: "Recipe.Serves").IfNegativeOrZero();
		Value = value;
	}

	/// <summary>
	/// Gets PositiveInt Value.
	/// </summary>
	public int Value { get; }

	/// <summary>
	/// Trys to create <see cref="PositiveInt"/>. Returns Error if it fails.
	/// <remarks>When value is null, will return IsError = true with empty list of errors.</remarks>
	/// </summary>
	/// <param name="value">Value of <see cref="PositiveInt"/>.</param>
	/// <returns><see cref="PositiveInt"/> or Validation Error.</returns>
	public static ErrorOr<PositiveInt> TryCreate(int? value) =>
		value switch
		{
			null => default,
			< 1 => RecipeError.ServesCannotBeNegative,
			_ => new PositiveInt(value.Value),
		};

	/// <inheritdoc />
	protected override IEnumerable<object> GetEqualityComponents()
	{
		yield return Value;
	}
}
```

Test for null:

```csharp
[Fact]
public void TryCreate_WhenValueIsNull_ShouldReturnDefault()
{
	var actual = PositiveInt.TryCreate(null);
	actual.IsError.Should().BeFalse();
	actual.ErrorsOrEmptyList.Should().BeEmpty();
	actual.Value.Should().BeNull();
}
```
