### ISSUE TITLE
Add Stacktrace property to the Error struct

### ISSUE THREAD

**Issue by YonatanCohavi** [amantinband/error-or#74]
Can you please add a "StrackTrace" string Property to the Error struct when creating a new exception. this will help with logging the errors and handling them.

**Comment by amantinband** [comment]
I motivation with keeping the `ErrorOr` object as small as possible was to improve performance.

Most applications don't actually return the stacktrace to the user but rather log them, so the current implementation pushes users to do something like the following:

```csharp
if (result.IsError)
{
    _logger.Log("whatever details are relavant");
    return result.Errors;
}
```

Does that make sense? what do you think?

**Comment by amantinband** [comment]
Version `1.5.0` added the `metadata` property which can be used to store extra properties #25

**Comment by YonatanCohavi** [comment]
Nice thanks!
