### ISSUE TITLE
[Request] Please sign the NuGet  with a strong name

### ISSUE THREAD

**Issue by YonatanCohavi** [amantinband/error-or#84]
First of all, thanks for this awesome project!
can you please sign this NuGet with a strong name? this will help to integrate it in a strong name solution.

**Comment by Foitn** [comment]
Yes please!

**Comment by amantinband** [comment]
Something like [StrongNamer](https://github.com/dsplaisted/strongnamer) or [StrongNameSigner](https://github.com/brutaldev/StrongNameSigner) should have you covered here. Let me know if this doesn't solve your issue
