### ISSUE TITLE
[Bug] Error equality not working as intended

### ISSUE THREAD

**Issue by HakonJohannessen** [amantinband/error-or#85]
Hi @amantinband, 
First of all I would like to thank you and all contributors for this great library :D 

My team and I recently decided to upgrade our ErrorOr version from 1.2.0 to 1.9.0 for the newest features, but quickly realized that this version brakes our automated tests. We have been writing tests asserting that the correct Error is returned for invalid input. For example, if we expect an `InvalidStartDepthError` we provide an instance of this error in our parameterized tests as `expectedError` and check that `occurredError.Should().BeEquivalent(expectedError)`.

The problem, as far as I can tell, seems to be related to how equality is handled for the Error class. After some research it appears the problem was introduced in version 1.4.0, when the "Metadata" property was added. In version **1.3.0**, we could write assertions like this:

```Csharp
[Test]
public void Errors_Should_Be_Equal()                                // Success
{
    var notFoundError = Error.NotFound("Question.NotFound", "Question Not Found");
    var sameNotFoundError = Error.NotFound("Question.NotFound", "Question Not Found");

    notFoundError.Should().Be(sameNotFoundError);
}

[Test]
public void Errors_Should_Be_Equivalent()                           // Success
{
    var notFoundError = Error.NotFound("Question.NotFound", "Question Not Found");
    var sameNotFoundError = Error.NotFound("Question.NotFound", "Question Not Found");

    notFoundError.Should().BeEquivalentTo(sameNotFoundError);
}
```

and the following would be the results checking equality manually:

```Csharp
var isEqual = notFoundError == sameNotFoundError;                  // true
var isEqualsEqual = notFoundError.Equals(sameNotFoundError);       // true
```

I would argue that this is the expected behavior.  

However, from version **1.4.0 and newer** this equivalence no longer holds:

```Csharp
[Test]
public void Errors_Should_Be_Equal()                                // Error
{
    var notFoundError = Error.NotFound(
        "Question.NotFound",
        "Question Not Found",
        new Dictionary<string, object> { { "answer_id", 42 } }
    );

    var sameNotFoundError = Error.NotFound(
        "Question.NotFound",
        "Question Not Found",
        new Dictionary<string, object> { { "answer_id", 42 } }
    );

    notFoundError.Should().Be(sameNotFoundError);
}

[Test]
public void Errors_Should_Be_Equivalent()                           // Error
{
    var notFoundError = Error.NotFound(
        "Question.NotFound",
        "Question Not Found",
        new Dictionary<string, object> { { "answer_id", 42 } }
    );

    var sameNotFoundError = Error.NotFound(
        "Question.NotFound",
        "Question Not Found",
        new Dictionary<string, object> { { "answer_id", 42 } }
    );

    notFoundError.Should().BeEquivalentTo(sameNotFoundError);
}
```

and the manual checks:

```Csharp
var isEqual = notFoundError == sameNotFoundError;                  // false
var isEqualsEqual = notFoundError.Equals(sameNotFoundError);       // false
```

I do note that the Error class already is marked `readonly record struct`, which should handle immutability and value-based equality. However, as demonstrated above this does not appear to be working as intended.

**Comment by amantinband** [comment]
hey @HakonJohannessen. I think comparing two `Error` record structs should behave the same as comparing any other C# record struct.

This is the behavior I would expect:
```cs
var notFoundError = Error.NotFound("Question.NotFound", "Question Not Found");
var sameNotFoundError = Error.NotFound("Question.NotFound", "Question Not Found");

notFoundError.Should().Be(sameNotFoundError); // true
notFoundError.Should().BeEquivalentTo(sameNotFoundError); // true
```

```cs
var notFoundError = Error.NotFound(
    "Question.NotFound",
    "Question Not Found",
    new Dictionary<string, object> { { "answer_id", 42 } });

var sameNotFoundError = Error.NotFound(
    "Question.NotFound",
    "Question Not Found",
    new Dictionary<string, object> { { "answer_id", 42 } });

notFoundError.Should().Be(sameNotFoundError); // false
notFoundError.Should().BeEquivalentTo(sameNotFoundError); // true
```

If the following doesn't work as expected:
```cs
var notFoundError = Error.NotFound(
    "Question.NotFound",
    "Question Not Found",
    new Dictionary<string, object> { { "answer_id", 42 } });

var sameNotFoundError = Error.NotFound(
    "Question.NotFound",
    "Question Not Found",
    new Dictionary<string, object> { { "answer_id", 42 } });

notFoundError.Should().BeEquivalentTo(sameNotFoundError); // false, but should be true
```

Make sure you have fluent assertions version > `6.9.0`.

Let me know if `BeEquivalentTo` still fails after updating the `FluentAssertions` package

**Comment by SteveDunn** [comment]
This is the trouble with using `record`s that don't exhibit value equality. I think it should override the equality operators, or better still, swap out the `Dictionary<K,V>` with a custom collection that exhibits value equality.
We could then have (or _also_ have) two overloads; one takes a `string` and a `value`, and the other takes a `params (string, object)[]`. Neither of these would expose the underlying mutable dictionary, which would have two benefits; immutability, and value equality.

**Comment by feO2x** [comment]
I'm currently struggling with the same issue. The project I'm working on uses ErrorOr v2.0.1. Additionally to the metadata, I found out that `ErrorOr<TValue>` has the same issues with error lists. For me, this has an influence on writing test code because instead of simply calling equals, I need to perform a deep comparison, usually with FluentAssertion's `Shoudl().BeEquivalentTo()` where I need to explicitly specify to compare by properties. The whole ugly call then looks like this:

```csharp
result.Should().BeEquivalentTo(expectedResult.ToErrorOr<Success>(), options => options.ComparingByMembers<ErrorOr<Success>>());
```

I don't think that we require a breaking change in the API, we could simply implement `Equals` and `GetHashCode` on our own and perform the proper collection/dictionary comparisons (records simply call the default equality comparer for each property and this performs a simple reference check for the error list and the metadata dictionary, respectively).

Would you mind if I prepare a PR for this issue?
