### ISSUE TITLE
Return ErrorOr<?>

### ISSUE THREAD

**Issue by BrunoferreiraOrbcom** [amantinband/error-or#89]
Hi!

Thank you very much for developing this package :)

I have an update command in which I would like to have void-like behavior.
How can I use ErrorOr<void> or something similar?

**Comment by bCamba** [comment]
Can you be more specific? Are you talking about command as in Mediator command using CQRS?

I think what you are looking for is something like this:

```

public record MyCommand() : IRequest<ErrorOr<Updated>>

public class MyHandler : IRequestHandler<MyCommand, ErrorOr<Updated>>
{
    public Task<ErrorOr<Updated>> Handle(MyCommand command, CancellationToken cancellationToken)
    {
        return Task.FromResult(Result.Updated);
    }
}

```

**Comment by BrunoferreiraOrbcom** [comment]
Hi!

Sorry for my lack of words. You're right. I'm using a update command following CQRS with MediatoR.
What I needed was a way to return nothing, or a Error, but the Result Enums seems indeed more adequate. I was not aware of this Enum, thank you for you time.
