### ISSUE TITLE
[Enhancement] Avoid duplicated runtime memory by moving NoFirstError and NoErrors into non-generic type

### ISSUE THREAD

**Issue by feO2x** [amantinband/error-or#98]
Currently, the `ErrorOr<TValue>` struct contains two static read-only fields called `NoFirstError` and `NoErrors` which are used to return error objects in the `FirstError` and `ErrorsOrEmptyList` properties. The issue is that for each type the generic `TValue` is resolved to during runtime, these two fields will be created and thus reside in memory several times (see [here](https://www.jetbrains.com/help/rider/StaticMemberInGenericType.html) for a detailed description).

These two errors should be moved into a different non-generic type. Additionally, we can cache some of the lists instead of instantiating them every time `Errors` or `ErrorsOrEmptyList` is called.

**Comment by amantinband** [comment]
Sweet thanks for this!
